[package]
name = "rust-wfa2"
version = "0.1.0"
edition = "2021"
include = ["src/**/*", "LICENSE.md", "README.md", "CHANGELOG.md"]

[workspace]
members = ["wfa2-sys"]

[dependencies]
serde = { version = "1.0.150", features = ["derive"] }
wfa2-sys = { version = "*", path = "wfa2-sys" }
